doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                # configure these for your database server
                url: '%env(resolve:DATABASE_URL)%'
                driver: 'pdo_mysql'
                server_version: 'mariadb-10.5.8'
                charset: utf8mb4
            codex:
                # configure these for your database server
                url: '%env(resolve:DATABASE_CODEX_URL)%'
                driver: 'pdo_mysql'
                server_version: 'mariadb-10.5.8'
                charset: utf8mb4
    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: true
        entity_managers:
            default:
                connection: default
                mappings:
                    Main:
                        is_bundle: false
                        # type: annotation
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
                        # dir: '%kernel.project_dir%/src/Entity/Main'
                        # prefix: 'App\Entity\Main'
                        # alias: Main
            codex:
                connection: codex
                mappings:
                    Codex:
                        is_bundle: false
                        # type: annotation
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Codex'
                        prefix: 'App\Entity\Codex'
                        alias: Codex

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
